- name: Configure web application
  hosts: all
  become: true
  tasks:
    - name: Copy configuration file
      copy:
        src: files/webapp.conf
        dest: /etc/webapp/webapp.conf
      notify:
        - Restart webapp
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - package1
        - package2
    # Add more tasks as needed
  handlers:
    - name: Restart webapp
      systemd:
        name: webapp
        state: restarted
